# Generated by Django 6.0.6 on 2026-06-27 14:50

import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], default='DNI', max_length=3)),
                ('numero_documento', models.CharField(help_text='8 dígitos para DNI, 11 dígitos para RUC', max_length=11, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[envios.validators.validar_telefono_peru])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
