# Generated by Django 6.0.6 on 2026-06-27 14:50

import django.db.models.deletion
import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Conductor', 'Conductor'), ('Operador', 'Operador')], default='Operador', max_length=20)),
                ('sucursal', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, validators=[envios.validators.validar_codigo_encomienda])),
                ('descripcion', models.TextField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6, validators=[envios.validators.validar_peso_positivo])),
                ('estado', models.CharField(choices=[('Registrado', 'Registrado'), ('En Ruta', 'En Ruta'), ('En Sucursal', 'En Sucursal'), ('Entregado', 'Entregado'), ('Devuelto', 'Devuelto')], default='Registrado', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateTimeField(help_text='Fecha estimada de entrega')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_destinatario', to='clientes.cliente')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_remitente', to='clientes.cliente')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas', to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Registrado', 'Registrado'), ('En Ruta', 'En Ruta'), ('En Sucursal', 'En Sucursal'), ('Entregado', 'Entregado'), ('Devuelto', 'Devuelto')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('detalle_observacion', models.TextField(blank=True, null=True)),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='envios.encomienda')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estado',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
